export const SYSTEM_MESSAGE_BATCH_SIZE = 50;
export const SYSTEM_MESSAGE_LEASE_MS = 30_000;
export const SYSTEM_MESSAGE_RETRY_BASE_MS = 10_000;
export const SYSTEM_MESSAGE_RETRY_MAX_MS = 15 * 60_000;
export const SYSTEM_MESSAGE_RETRY_WINDOW_MS = 24 * 60 * 60_000;
export const SYSTEM_MESSAGE_DDNS_RECHECK_MS = 60_000;
export const SYSTEM_MESSAGE_SCAN_INTERVAL_MS = 5_000;
