export const MEDIA_FILE_SELECTION = Object.freeze({
  synchronizationTemporaryPath: /(?:^|\/)(?:\.syncthing\.|~syncthing~)/iu,
  videoSuffix: /\.(?:avi|m2ts|m4v|mkv|mov|mp4|ts|webm)$/iu,
  subtitleSuffix: /\.(?:ass|ssa|srt|sup|vtt)$/iu,
  episodeMarker:
    /(?:^|[^a-z0-9])(?:S(\d{1,2}))?E(?:P)?\s*(\d{1,4})(?![a-z0-9])/giu,
  episodeRange: /^\s*[-~–]\s*(?:E(?:P)?)?\d/iu,
  bracketEpisode: /\[(\d{1,3})\]/gu,
  independentNumber: /(?:^|[._ -])(\d{1,3})(?=$|[._ \[\]()-])/gu,
  maxEpisode: 2000,
  ambiguousMapping: '来源自动选择存在重复或不完整映射，请手动复核',
  minimumFeatureBytes: 512 * 1024 * 1024,
  maximumIncidentalBytes: 64 * 1024 * 1024,
  minimumDominanceRatio: 8,
  movieAmbiguous: '电影来源无法唯一自动判断正片，请手动选择',
  unitMissing: '任务缺少治理单元',
  invalidMapping: '来源文件尚未完成一对一治理映射',
  movieUnitLabel: '电影单元',
  missingVideo: (unit: string) => `${unit} 缺少已映射视频`,
  missingSubtitle: (unit: string) => `${unit} 中文字幕映射不完整`,
  missingSubtitleContract: (unit: string) => `${unit} 缺少完整字幕合同`,
  movieSubtitleSource: '电影外挂简体中文字幕必须由唯一补充来源提供',
  subtitleSourceMismatch: '字幕合同来源或发布组不匹配',
  subtitleMappingMismatch: '字幕合同与密封文件映射不一致',
});
